# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 191b5c75674c2e03beccbd47766947196886c5e49cd746b2446e84627ec6568e89384700e1d04cd3361186d9b9ed8ffe0971ffc50186592bbd4ae28d2711e571

test:
  secret_key_base: 5eb4df3347a00ff2eb501dab6d84c671075935d3f2a4f414d68e0c9a369d552444320e798f10d41e10fbb0f717a3ae816e42932d5bc25f43e230dab55b28a42b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
